/* automatically generated by rust-bindgen 0.72.1 */

pub const SCITER_VERSION_0: u32 = 6;
pub const SCITER_VERSION_1: u32 = 0;
pub const SCITER_VERSION_2: u32 = 4;
pub const SCITER_VERSION_3: u32 = 9;
pub const SCITER_API_VERSION: u32 = 10;
pub type wchar_t = ::core::ffi::c_ushort;
pub type SBOOL = ::core::ffi::c_int;
pub type BYTE = ::core::ffi::c_uchar;
pub type LPVOID = *mut ::core::ffi::c_void;
pub type INT = ::core::ffi::c_int;
pub type UINT = ::core::ffi::c_uint;
pub type INT64 = ::core::ffi::c_longlong;
pub type UINT64 = ::core::ffi::c_ulonglong;
pub type INT_PTR = ::core::ffi::c_longlong;
pub type UINT_PTR = ::core::ffi::c_ulonglong;
pub type LONG_PTR = ::core::ffi::c_longlong;
pub type CHAR = ::core::ffi::c_char;
pub type LONG = ::core::ffi::c_long;
pub type WCHAR = wchar_t;
pub type LPWSTR = *mut WCHAR;
pub type LPCWSTR = *const WCHAR;
pub type LPCSTR = *const CHAR;
pub type WPARAM = UINT_PTR;
pub type LPARAM = LONG_PTR;
pub type LRESULT = LONG_PTR;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HWND__ {
    pub unused: ::core::ffi::c_int,
}
pub type HWND = *mut HWND__;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagRECT {
    pub left: LONG,
    pub top: LONG,
    pub right: LONG,
    pub bottom: LONG,
}
pub type RECT = tagRECT;
pub type LPRECT = *mut tagRECT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagPOINT {
    pub x: LONG,
    pub y: LONG,
}
pub type POINT = tagPOINT;
pub type LPPOINT = *mut tagPOINT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagSIZE {
    pub cx: LONG,
    pub cy: LONG,
}
pub type LPSIZE = *mut tagSIZE;
pub type LPUINT = *mut UINT;
pub type LPCBYTE = *const BYTE;
pub type HREQUEST = *mut ::core::ffi::c_void;
pub const REQUEST_RESULT_REQUEST_PANIC: REQUEST_RESULT = -1;
pub const REQUEST_RESULT_REQUEST_OK: REQUEST_RESULT = 0;
pub const REQUEST_RESULT_REQUEST_BAD_PARAM: REQUEST_RESULT = 1;
pub const REQUEST_RESULT_REQUEST_FAILURE: REQUEST_RESULT = 2;
pub const REQUEST_RESULT_REQUEST_NOTSUPPORTED: REQUEST_RESULT = 3;
pub type REQUEST_RESULT = ::core::ffi::c_int;
pub const SciterResourceType_RT_DATA_HTML: SciterResourceType = 0;
pub const SciterResourceType_RT_DATA_IMAGE: SciterResourceType = 1;
pub const SciterResourceType_RT_DATA_STYLE: SciterResourceType = 2;
pub const SciterResourceType_RT_DATA_CURSOR: SciterResourceType = 3;
pub const SciterResourceType_RT_DATA_SCRIPT: SciterResourceType = 4;
pub const SciterResourceType_RT_DATA_RAW: SciterResourceType = 5;
pub const SciterResourceType_RT_DATA_FONT: SciterResourceType = 6;
pub const SciterResourceType_RT_DATA_MEDIA: SciterResourceType = 7;
pub const SciterResourceType_RT_DATA_FORCE_DWORD: SciterResourceType = -1;
pub type SciterResourceType = ::core::ffi::c_int;
pub const REQUEST_STATE_RS_PENDING: REQUEST_STATE = 0;
pub const REQUEST_STATE_RS_SUCCESS: REQUEST_STATE = 1;
pub const REQUEST_STATE_RS_FAILURE: REQUEST_STATE = 2;
pub const REQUEST_STATE_RS_FORCE_DWORD: REQUEST_STATE = -1;
pub type REQUEST_STATE = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HELEMENT {
    _unused: [u8; 0],
}
#[doc = "DOM element handle."]
pub type HELEMENT = *mut _HELEMENT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SciterRequestAPI {
    pub RequestUse: ::core::option::Option<unsafe extern "C" fn(rq: HREQUEST) -> REQUEST_RESULT>,
    pub RequestUnUse: ::core::option::Option<unsafe extern "C" fn(rq: HREQUEST) -> REQUEST_RESULT>,
    pub RequestUrl: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestContentUrl: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetRequestType: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, pType: *mut LPCSTR) -> REQUEST_RESULT,
    >,
    pub RequestGetRequestedDataType: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, pData: *mut SciterResourceType) -> REQUEST_RESULT,
    >,
    pub RequestGetReceivedDataType: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetNumberOfParameters: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, pNumber: *mut UINT) -> REQUEST_RESULT,
    >,
    pub RequestGetNthParameterName: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            n: UINT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetNthParameterValue: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            n: UINT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetTimes: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            pStarted: *mut UINT,
            pEnded: *mut UINT,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetNumberOfRqHeaders: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, pNumber: *mut UINT) -> REQUEST_RESULT,
    >,
    pub RequestGetNthRqHeaderName: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            n: UINT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetNthRqHeaderValue: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            n: UINT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetNumberOfRspHeaders: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, pNumber: *mut UINT) -> REQUEST_RESULT,
    >,
    pub RequestGetNthRspHeaderName: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            n: UINT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetNthRspHeaderValue: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            n: UINT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetCompletionStatus: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            pState: *mut REQUEST_STATE,
            pCompletionStatus: *mut UINT,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetProxyHost: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetProxyPort: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, pPort: *mut UINT) -> REQUEST_RESULT,
    >,
    pub RequestSetSucceeded: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            status: UINT,
            dataOrNull: LPCBYTE,
            dataLength: UINT,
        ) -> REQUEST_RESULT,
    >,
    pub RequestSetFailed: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            status: UINT,
            dataOrNull: LPCBYTE,
            dataLength: UINT,
        ) -> REQUEST_RESULT,
    >,
    pub RequestAppendDataChunk: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, data: LPCBYTE, dataLength: UINT) -> REQUEST_RESULT,
    >,
    pub RequestSetRqHeader: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, name: LPCWSTR, value: LPCWSTR) -> REQUEST_RESULT,
    >,
    pub RequestSetRspHeader: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, name: LPCWSTR, value: LPCWSTR) -> REQUEST_RESULT,
    >,
    pub RequestSetReceivedDataType:
        ::core::option::Option<unsafe extern "C" fn(rq: HREQUEST, type_: LPCSTR) -> REQUEST_RESULT>,
    pub RequestSetReceivedDataEncoding: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, encoding: LPCSTR) -> REQUEST_RESULT,
    >,
    pub RequestGetData: ::core::option::Option<
        unsafe extern "C" fn(
            rq: HREQUEST,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCBYTE, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> REQUEST_RESULT,
    >,
    pub RequestGetRequestor: ::core::option::Option<
        unsafe extern "C" fn(rq: HREQUEST, pElement: *mut HELEMENT) -> REQUEST_RESULT,
    >,
}
pub type LPSciterRequestAPI = *mut SciterRequestAPI;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VALUE {
    pub t: UINT,
    pub u: UINT,
    pub d: UINT64,
}
pub type NATIVE_FUNCTOR_INVOKE = ::core::option::Option<
    unsafe extern "C" fn(
        tag: *mut ::core::ffi::c_void,
        argc: UINT,
        argv: *const VALUE,
        retval: *mut VALUE,
    ),
>;
pub type NATIVE_FUNCTOR_RELEASE =
    ::core::option::Option<unsafe extern "C" fn(tag: *mut ::core::ffi::c_void)>;
pub type SCITER_VALUE = VALUE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HNODE {
    _unused: [u8; 0],
}
pub type HNODE = *mut _HNODE;
#[doc = "DOM range handle."]
pub type HSARCHIVE = *mut ::core::ffi::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct METHOD_PARAMS {
    pub methodID: UINT,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct REQUEST_PARAM {
    pub name: LPCWSTR,
    pub value: LPCWSTR,
}
pub type LPELEMENT_EVENT_PROC = ::core::option::Option<
    unsafe extern "C" fn(arg1: LPVOID, arg2: HELEMENT, arg3: UINT, arg4: LPVOID) -> SBOOL,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HGFX {
    _unused: [u8; 0],
}
pub type HGFX = *mut _HGFX;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HIMG {
    _unused: [u8; 0],
}
pub type HIMG = *mut _HIMG;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HPATH {
    _unused: [u8; 0],
}
pub type HPATH = *mut _HPATH;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _HTEXT {
    _unused: [u8; 0],
}
pub type HTEXT = *mut _HTEXT;
pub type SC_REAL = f32;
pub type SC_POS = SC_REAL;
pub type SC_DIM = SC_REAL;
pub type SC_ANGLE = SC_REAL;
pub type SC_COLOR = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SC_COLOR_STOP {
    pub color: SC_COLOR,
    pub offset: f32,
}
pub const GRAPHIN_RESULT_GRAPHIN_PANIC: GRAPHIN_RESULT = -1;
pub const GRAPHIN_RESULT_GRAPHIN_OK: GRAPHIN_RESULT = 0;
pub const GRAPHIN_RESULT_GRAPHIN_BAD_PARAM: GRAPHIN_RESULT = 1;
pub const GRAPHIN_RESULT_GRAPHIN_FAILURE: GRAPHIN_RESULT = 2;
pub const GRAPHIN_RESULT_GRAPHIN_NOTSUPPORTED: GRAPHIN_RESULT = 3;
pub type GRAPHIN_RESULT = ::core::ffi::c_int;
pub const DRAW_PATH_MODE_DRAW_FILL_ONLY: DRAW_PATH_MODE = 1;
pub const DRAW_PATH_MODE_DRAW_STROKE_ONLY: DRAW_PATH_MODE = 2;
pub const DRAW_PATH_MODE_DRAW_FILL_AND_STROKE: DRAW_PATH_MODE = 3;
pub type DRAW_PATH_MODE = ::core::ffi::c_int;
pub const SCITER_LINE_JOIN_TYPE_SCITER_JOIN_MITER: SCITER_LINE_JOIN_TYPE = 0;
pub const SCITER_LINE_JOIN_TYPE_SCITER_JOIN_ROUND: SCITER_LINE_JOIN_TYPE = 1;
pub const SCITER_LINE_JOIN_TYPE_SCITER_JOIN_BEVEL: SCITER_LINE_JOIN_TYPE = 2;
pub const SCITER_LINE_JOIN_TYPE_SCITER_JOIN_MITER_OR_BEVEL: SCITER_LINE_JOIN_TYPE = 3;
pub type SCITER_LINE_JOIN_TYPE = ::core::ffi::c_int;
pub const SCITER_LINE_CAP_TYPE_SCITER_LINE_CAP_BUTT: SCITER_LINE_CAP_TYPE = 0;
pub const SCITER_LINE_CAP_TYPE_SCITER_LINE_CAP_SQUARE: SCITER_LINE_CAP_TYPE = 1;
pub const SCITER_LINE_CAP_TYPE_SCITER_LINE_CAP_ROUND: SCITER_LINE_CAP_TYPE = 2;
pub type SCITER_LINE_CAP_TYPE = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SciterGraphicsAPI {
    pub imageCreate: ::core::option::Option<
        unsafe extern "C" fn(
            poutImg: *mut HIMG,
            width: UINT,
            height: UINT,
            withAlpha: SBOOL,
        ) -> GRAPHIN_RESULT,
    >,
    pub imageCreateFromPixmap: ::core::option::Option<
        unsafe extern "C" fn(
            poutImg: *mut HIMG,
            pixmapWidth: UINT,
            pixmapHeight: UINT,
            pixmap_format: UINT,
            pixmap: *const BYTE,
        ) -> GRAPHIN_RESULT,
    >,
    pub imageAddRef: ::core::option::Option<unsafe extern "C" fn(himg: HIMG) -> GRAPHIN_RESULT>,
    pub imageRelease: ::core::option::Option<unsafe extern "C" fn(himg: HIMG) -> GRAPHIN_RESULT>,
    pub imageGetInfo: ::core::option::Option<
        unsafe extern "C" fn(
            himg: HIMG,
            width: *mut UINT,
            height: *mut UINT,
            usesAlpha: *mut SBOOL,
        ) -> GRAPHIN_RESULT,
    >,
    pub imageClear: ::core::option::Option<
        unsafe extern "C" fn(himg: HIMG, byColor: SC_COLOR) -> GRAPHIN_RESULT,
    >,
    pub imageLoad: ::core::option::Option<
        unsafe extern "C" fn(
            bytes: *const BYTE,
            num_bytes: UINT,
            pout_img: *mut HIMG,
        ) -> GRAPHIN_RESULT,
    >,
    pub imageSave: ::core::option::Option<
        unsafe extern "C" fn(
            himg: HIMG,
            pfn: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPVOID, arg2: *const BYTE, arg3: UINT) -> SBOOL,
            >,
            prm: *mut ::core::ffi::c_void,
            encoding: UINT,
            quality: UINT,
        ) -> GRAPHIN_RESULT,
    >,
    pub RGBA: ::core::option::Option<
        unsafe extern "C" fn(red: UINT, green: UINT, blue: UINT, alpha: UINT) -> SC_COLOR,
    >,
    pub gCreate: ::core::option::Option<
        unsafe extern "C" fn(img: HIMG, pout_gfx: *mut HGFX) -> GRAPHIN_RESULT,
    >,
    pub gAddRef: ::core::option::Option<unsafe extern "C" fn(gfx: HGFX) -> GRAPHIN_RESULT>,
    pub gRelease: ::core::option::Option<unsafe extern "C" fn(gfx: HGFX) -> GRAPHIN_RESULT>,
    pub gLine: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x1: SC_POS,
            y1: SC_POS,
            x2: SC_POS,
            y2: SC_POS,
        ) -> GRAPHIN_RESULT,
    >,
    pub gRectangle: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x1: SC_POS,
            y1: SC_POS,
            x2: SC_POS,
            y2: SC_POS,
        ) -> GRAPHIN_RESULT,
    >,
    pub gRoundedRectangle: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x1: SC_POS,
            y1: SC_POS,
            x2: SC_POS,
            y2: SC_POS,
            radii8: *const SC_DIM,
        ) -> GRAPHIN_RESULT,
    >,
    pub gEllipse: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x: SC_POS,
            y: SC_POS,
            rx: SC_DIM,
            ry: SC_DIM,
        ) -> GRAPHIN_RESULT,
    >,
    pub gArc: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x: SC_POS,
            y: SC_POS,
            rx: SC_POS,
            ry: SC_POS,
            start: SC_ANGLE,
            sweep: SC_ANGLE,
        ) -> GRAPHIN_RESULT,
    >,
    pub gStar: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x: SC_POS,
            y: SC_POS,
            r1: SC_DIM,
            r2: SC_DIM,
            start: SC_ANGLE,
            rays: UINT,
        ) -> GRAPHIN_RESULT,
    >,
    pub gPolygon: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, xy: *const SC_POS, num_points: UINT) -> GRAPHIN_RESULT,
    >,
    pub gPolyline: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, xy: *const SC_POS, num_points: UINT) -> GRAPHIN_RESULT,
    >,
    pub pathCreate:
        ::core::option::Option<unsafe extern "C" fn(path: *mut HPATH) -> GRAPHIN_RESULT>,
    pub pathAddRef: ::core::option::Option<unsafe extern "C" fn(path: HPATH) -> GRAPHIN_RESULT>,
    pub pathRelease: ::core::option::Option<unsafe extern "C" fn(path: HPATH) -> GRAPHIN_RESULT>,
    pub pathMoveTo: ::core::option::Option<
        unsafe extern "C" fn(path: HPATH, x: SC_POS, y: SC_POS, relative: SBOOL) -> GRAPHIN_RESULT,
    >,
    pub pathLineTo: ::core::option::Option<
        unsafe extern "C" fn(path: HPATH, x: SC_POS, y: SC_POS, relative: SBOOL) -> GRAPHIN_RESULT,
    >,
    pub pathArcTo: ::core::option::Option<
        unsafe extern "C" fn(
            path: HPATH,
            x: SC_POS,
            y: SC_POS,
            angle: SC_ANGLE,
            rx: SC_DIM,
            ry: SC_DIM,
            is_large_arc: SBOOL,
            clockwise: SBOOL,
            relative: SBOOL,
        ) -> GRAPHIN_RESULT,
    >,
    pub pathQuadraticCurveTo: ::core::option::Option<
        unsafe extern "C" fn(
            path: HPATH,
            xc: SC_POS,
            yc: SC_POS,
            x: SC_POS,
            y: SC_POS,
            relative: SBOOL,
        ) -> GRAPHIN_RESULT,
    >,
    pub pathBezierCurveTo: ::core::option::Option<
        unsafe extern "C" fn(
            path: HPATH,
            xc1: SC_POS,
            yc1: SC_POS,
            xc2: SC_POS,
            yc2: SC_POS,
            x: SC_POS,
            y: SC_POS,
            relative: SBOOL,
        ) -> GRAPHIN_RESULT,
    >,
    pub pathClosePath: ::core::option::Option<unsafe extern "C" fn(path: HPATH) -> GRAPHIN_RESULT>,
    pub gDrawPath: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, path: HPATH, dpm: DRAW_PATH_MODE) -> GRAPHIN_RESULT,
    >,
    pub gRotate: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            radians: SC_ANGLE,
            cx: *const SC_POS,
            cy: *const SC_POS,
        ) -> GRAPHIN_RESULT,
    >,
    pub gTranslate: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, cx: SC_POS, cy: SC_POS) -> GRAPHIN_RESULT,
    >,
    pub gScale: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, x: SC_DIM, y: SC_DIM) -> GRAPHIN_RESULT,
    >,
    pub gSkew: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, dx: SC_DIM, dy: SC_DIM) -> GRAPHIN_RESULT,
    >,
    pub gTransform: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            m11: SC_POS,
            m12: SC_POS,
            m21: SC_POS,
            m22: SC_POS,
            dx: SC_POS,
            dy: SC_POS,
        ) -> GRAPHIN_RESULT,
    >,
    pub gStateSave: ::core::option::Option<unsafe extern "C" fn(hgfx: HGFX) -> GRAPHIN_RESULT>,
    pub gStateRestore: ::core::option::Option<unsafe extern "C" fn(hgfx: HGFX) -> GRAPHIN_RESULT>,
    pub gLineWidth:
        ::core::option::Option<unsafe extern "C" fn(hgfx: HGFX, width: SC_DIM) -> GRAPHIN_RESULT>,
    pub gLineJoin: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, type_: SCITER_LINE_JOIN_TYPE) -> GRAPHIN_RESULT,
    >,
    pub gLineCap: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, type_: SCITER_LINE_CAP_TYPE) -> GRAPHIN_RESULT,
    >,
    pub gLineColor:
        ::core::option::Option<unsafe extern "C" fn(hgfx: HGFX, c: SC_COLOR) -> GRAPHIN_RESULT>,
    pub gFillColor:
        ::core::option::Option<unsafe extern "C" fn(hgfx: HGFX, color: SC_COLOR) -> GRAPHIN_RESULT>,
    pub gLineGradientLinear: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x1: SC_POS,
            y1: SC_POS,
            x2: SC_POS,
            y2: SC_POS,
            stops: *const SC_COLOR_STOP,
            nstops: UINT,
        ) -> GRAPHIN_RESULT,
    >,
    pub gFillGradientLinear: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x1: SC_POS,
            y1: SC_POS,
            x2: SC_POS,
            y2: SC_POS,
            stops: *const SC_COLOR_STOP,
            nstops: UINT,
        ) -> GRAPHIN_RESULT,
    >,
    pub gLineGradientRadial: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x: SC_POS,
            y: SC_POS,
            rx: SC_DIM,
            ry: SC_DIM,
            stops: *const SC_COLOR_STOP,
            nstops: UINT,
        ) -> GRAPHIN_RESULT,
    >,
    pub gFillGradientRadial: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x: SC_POS,
            y: SC_POS,
            rx: SC_DIM,
            ry: SC_DIM,
            stops: *const SC_COLOR_STOP,
            nstops: UINT,
        ) -> GRAPHIN_RESULT,
    >,
    pub gFillMode:
        ::core::option::Option<unsafe extern "C" fn(hgfx: HGFX, even_odd: SBOOL) -> GRAPHIN_RESULT>,
    pub textCreateForElement: ::core::option::Option<
        unsafe extern "C" fn(
            ptext: *mut HTEXT,
            text: LPCWSTR,
            textLength: UINT,
            he: HELEMENT,
            classNameOrNull: LPCWSTR,
        ) -> GRAPHIN_RESULT,
    >,
    pub textCreateForElementAndStyle: ::core::option::Option<
        unsafe extern "C" fn(
            ptext: *mut HTEXT,
            text: LPCWSTR,
            textLength: UINT,
            he: HELEMENT,
            style: LPCWSTR,
            styleLength: UINT,
        ) -> GRAPHIN_RESULT,
    >,
    pub textAddRef: ::core::option::Option<unsafe extern "C" fn(path: HTEXT) -> GRAPHIN_RESULT>,
    pub textRelease: ::core::option::Option<unsafe extern "C" fn(path: HTEXT) -> GRAPHIN_RESULT>,
    pub textGetMetrics: ::core::option::Option<
        unsafe extern "C" fn(
            text: HTEXT,
            minWidth: *mut SC_DIM,
            maxWidth: *mut SC_DIM,
            height: *mut SC_DIM,
            ascent: *mut SC_DIM,
            descent: *mut SC_DIM,
            nLines: *mut UINT,
        ) -> GRAPHIN_RESULT,
    >,
    pub textSetBox: ::core::option::Option<
        unsafe extern "C" fn(text: HTEXT, width: SC_DIM, height: SC_DIM) -> GRAPHIN_RESULT,
    >,
    pub gDrawText: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            text: HTEXT,
            px: SC_POS,
            py: SC_POS,
            position: UINT,
        ) -> GRAPHIN_RESULT,
    >,
    pub gDrawImage: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            himg: HIMG,
            x: SC_POS,
            y: SC_POS,
            w: *const SC_DIM,
            h: *const SC_DIM,
            ix: *const UINT,
            iy: *const UINT,
            iw: *const UINT,
            ih: *const UINT,
            opacity: *const f32,
        ) -> GRAPHIN_RESULT,
    >,
    pub gWorldToScreen: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            inout_x: *mut SC_POS,
            inout_y: *mut SC_POS,
        ) -> GRAPHIN_RESULT,
    >,
    pub gScreenToWorld: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            inout_x: *mut SC_POS,
            inout_y: *mut SC_POS,
        ) -> GRAPHIN_RESULT,
    >,
    pub gPushClipBox: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            x1: SC_POS,
            y1: SC_POS,
            x2: SC_POS,
            y2: SC_POS,
            opacity: f32,
        ) -> GRAPHIN_RESULT,
    >,
    pub gPushClipPath: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, hpath: HPATH, opacity: f32) -> GRAPHIN_RESULT,
    >,
    pub gPopClip: ::core::option::Option<unsafe extern "C" fn(hgfx: HGFX) -> GRAPHIN_RESULT>,
    pub imagePaint: ::core::option::Option<
        unsafe extern "C" fn(
            himg: HIMG,
            pPainter: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPVOID, arg2: HGFX, arg3: UINT, arg4: UINT),
            >,
            prm: *mut ::core::ffi::c_void,
        ) -> GRAPHIN_RESULT,
    >,
    pub vWrapGfx: ::core::option::Option<
        unsafe extern "C" fn(hgfx: HGFX, toValue: *mut VALUE) -> GRAPHIN_RESULT,
    >,
    pub vWrapImage: ::core::option::Option<
        unsafe extern "C" fn(himg: HIMG, toValue: *mut VALUE) -> GRAPHIN_RESULT,
    >,
    pub vWrapPath: ::core::option::Option<
        unsafe extern "C" fn(hpath: HPATH, toValue: *mut VALUE) -> GRAPHIN_RESULT,
    >,
    pub vWrapText: ::core::option::Option<
        unsafe extern "C" fn(htext: HTEXT, toValue: *mut VALUE) -> GRAPHIN_RESULT,
    >,
    pub vUnWrapGfx: ::core::option::Option<
        unsafe extern "C" fn(fromValue: *const VALUE, phgfx: *mut HGFX) -> GRAPHIN_RESULT,
    >,
    pub vUnWrapImage: ::core::option::Option<
        unsafe extern "C" fn(fromValue: *const VALUE, phimg: *mut HIMG) -> GRAPHIN_RESULT,
    >,
    pub vUnWrapPath: ::core::option::Option<
        unsafe extern "C" fn(fromValue: *const VALUE, phpath: *mut HPATH) -> GRAPHIN_RESULT,
    >,
    pub vUnWrapText: ::core::option::Option<
        unsafe extern "C" fn(fromValue: *const VALUE, phtext: *mut HTEXT) -> GRAPHIN_RESULT,
    >,
    pub gFlush: ::core::option::Option<unsafe extern "C" fn(hgfx: HGFX) -> GRAPHIN_RESULT>,
    pub imageCreateFromElement: ::core::option::Option<
        unsafe extern "C" fn(poutImg: *mut HIMG, domElement: HELEMENT) -> GRAPHIN_RESULT,
    >,
    pub gGetNativeDC: ::core::option::Option<
        unsafe extern "C" fn(
            hgfx: HGFX,
            nativeDcType: UINT,
            pDC: *mut *mut ::core::ffi::c_void,
        ) -> GRAPHIN_RESULT,
    >,
}
pub type LPSciterGraphicsAPI = *mut SciterGraphicsAPI;
pub type som_atom_t = UINT64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct som_asset_t {
    pub isa: *mut som_asset_class_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct som_asset_class_t {
    pub asset_add_ref: ::core::option::Option<
        unsafe extern "C" fn(thing: *mut som_asset_t) -> ::core::ffi::c_long,
    >,
    pub asset_release: ::core::option::Option<
        unsafe extern "C" fn(thing: *mut som_asset_t) -> ::core::ffi::c_long,
    >,
    pub asset_get_interface: ::core::option::Option<
        unsafe extern "C" fn(
            thing: *mut som_asset_t,
            name: *const ::core::ffi::c_char,
            out: *mut *mut ::core::ffi::c_void,
        ) -> ::core::ffi::c_long,
    >,
    pub asset_get_passport: ::core::option::Option<
        unsafe extern "C" fn(thing: *mut som_asset_t) -> *mut som_passport_t,
    >,
}
pub type som_prop_getter_t = ::core::option::Option<
    unsafe extern "C" fn(thing: *mut som_asset_t, p_value: *mut SCITER_VALUE) -> SBOOL,
>;
pub type som_prop_setter_t = ::core::option::Option<
    unsafe extern "C" fn(thing: *mut som_asset_t, p_value: *mut SCITER_VALUE) -> SBOOL,
>;
pub type som_item_getter_t = ::core::option::Option<
    unsafe extern "C" fn(
        thing: *mut som_asset_t,
        p_key: *const SCITER_VALUE,
        p_value: *mut SCITER_VALUE,
    ) -> SBOOL,
>;
pub type som_item_setter_t = ::core::option::Option<
    unsafe extern "C" fn(
        thing: *mut som_asset_t,
        p_key: *const SCITER_VALUE,
        p_value: *const SCITER_VALUE,
    ) -> SBOOL,
>;
pub type som_item_next_t = ::core::option::Option<
    unsafe extern "C" fn(
        thing: *mut som_asset_t,
        p_idx: *mut SCITER_VALUE,
        p_value: *mut SCITER_VALUE,
    ) -> SBOOL,
>;
pub type som_any_prop_getter_t = ::core::option::Option<
    unsafe extern "C" fn(
        thing: *mut som_asset_t,
        propSymbol: UINT64,
        p_value: *mut SCITER_VALUE,
    ) -> SBOOL,
>;
pub type som_any_prop_setter_t = ::core::option::Option<
    unsafe extern "C" fn(
        thing: *mut som_asset_t,
        propSymbol: UINT64,
        p_value: *const SCITER_VALUE,
    ) -> SBOOL,
>;
pub type som_method_t = ::core::option::Option<
    unsafe extern "C" fn(
        thing: *mut som_asset_t,
        argc: UINT,
        argv: *const SCITER_VALUE,
        p_result: *mut SCITER_VALUE,
    ) -> SBOOL,
>;
pub type som_name_resolver_t = ::core::option::Option<
    unsafe extern "C" fn(
        thing: *mut som_asset_t,
        propSymbol: som_atom_t,
        pIndex: *mut UINT,
        pIsMethod: *mut SBOOL,
    ) -> SBOOL,
>;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct som_property_def_t {
    pub type_: isize,
    pub name: som_atom_t,
    pub u: som_property_def_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union som_property_def_t__bindgen_ty_1 {
    pub accs: som_property_def_t__bindgen_ty_1__bindgen_ty_1,
    pub i32_: i32,
    pub i64_: i64,
    pub f64_: f64,
    pub str_: *const ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct som_property_def_t__bindgen_ty_1__bindgen_ty_1 {
    pub getter: som_prop_getter_t,
    pub setter: som_prop_setter_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct som_method_def_t {
    pub reserved: *mut ::core::ffi::c_void,
    pub name: som_atom_t,
    pub params: usize,
    pub func: som_method_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct som_passport_t {
    pub flags: UINT64,
    pub name: som_atom_t,
    pub properties: *const som_property_def_t,
    pub n_properties: usize,
    pub methods: *const som_method_def_t,
    pub n_methods: usize,
    pub item_getter: som_item_getter_t,
    pub item_setter: som_item_setter_t,
    pub item_next: som_item_next_t,
    pub prop_getter: som_any_prop_getter_t,
    pub prop_setter: som_any_prop_setter_t,
    pub name_resolver: som_name_resolver_t,
    pub reserved: *mut ::core::ffi::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BEHAVIOR_EVENT_PARAMS {
    pub cmd: UINT,
    pub heTarget: HELEMENT,
    pub he: HELEMENT,
    pub reason: UINT_PTR,
    pub data: SCITER_VALUE,
    pub name: LPCWSTR,
}
#[doc = "Notification callback structure."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SCITER_CALLBACK_NOTIFICATION {
    #[doc = "< [in] one of the codes above."]
    pub code: UINT,
    #[doc = "< [in] HWINDOW of the window this callback was attached to."]
    pub hwnd: HWND,
}
pub type LPSCITER_CALLBACK_NOTIFICATION = *mut SCITER_CALLBACK_NOTIFICATION;
pub type LPSciterHostCallback = ::core::option::Option<
    unsafe extern "C" fn(arg1: LPSCITER_CALLBACK_NOTIFICATION, arg2: LPVOID) -> UINT,
>;
pub type DEBUG_OUTPUT_PROC = ::core::option::Option<
    unsafe extern "C" fn(
        param: LPVOID,
        subsystem: UINT,
        severity: UINT,
        text: LPCWSTR,
        text_length: UINT,
    ),
>;
#[doc = " #SCITER_X_MSG common header of message structures passed to SciterProcX"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SCITER_X_MSG {
    #[doc = "< [in]  one of the codes of #SCITER_X_MSG_CODE."]
    pub msg: UINT,
}
pub type proc_ptr_t = ::core::option::Option<unsafe extern "C" fn()>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ISciterAPI {
    pub version: UINT,
    pub SciterClassName: ::core::option::Option<unsafe extern "C" fn() -> LPCWSTR>,
    pub SciterVersion: ::core::option::Option<unsafe extern "C" fn(n: UINT) -> UINT>,
    pub SciterDataReady: ::core::option::Option<
        unsafe extern "C" fn(hwnd: HWND, uri: LPCWSTR, data: LPCBYTE, dataLength: UINT) -> SBOOL,
    >,
    pub SciterDataReadyAsync: ::core::option::Option<
        unsafe extern "C" fn(
            hwnd: HWND,
            uri: LPCWSTR,
            data: LPCBYTE,
            dataLength: UINT,
            requestId: LPVOID,
        ) -> SBOOL,
    >,
    pub SciterProc: ::core::option::Option<
        unsafe extern "C" fn(hwnd: HWND, msg: UINT, wParam: WPARAM, lParam: LPARAM) -> LRESULT,
    >,
    pub SciterProcND: ::core::option::Option<
        unsafe extern "C" fn(
            hwnd: HWND,
            msg: UINT,
            wParam: WPARAM,
            lParam: LPARAM,
            pbHandled: *mut SBOOL,
        ) -> LRESULT,
    >,
    pub SciterLoadFile:
        ::core::option::Option<unsafe extern "C" fn(hWndSciter: HWND, filename: LPCWSTR) -> SBOOL>,
    pub SciterLoadHtml: ::core::option::Option<
        unsafe extern "C" fn(
            hWndSciter: HWND,
            html: LPCBYTE,
            htmlSize: UINT,
            baseUrl: LPCWSTR,
        ) -> SBOOL,
    >,
    pub SciterSetCallback: ::core::option::Option<
        unsafe extern "C" fn(hWndSciter: HWND, cb: LPSciterHostCallback, cbParam: LPVOID),
    >,
    pub SciterSetMasterCSS:
        ::core::option::Option<unsafe extern "C" fn(utf8: LPCBYTE, numBytes: UINT) -> SBOOL>,
    pub SciterAppendMasterCSS:
        ::core::option::Option<unsafe extern "C" fn(utf8: LPCBYTE, numBytes: UINT) -> SBOOL>,
    pub SciterSetCSS: ::core::option::Option<
        unsafe extern "C" fn(
            hWndSciter: HWND,
            utf8: LPCBYTE,
            numBytes: UINT,
            baseUrl: LPCWSTR,
            mediaType: LPCWSTR,
        ) -> SBOOL,
    >,
    pub SciterSetMediaType:
        ::core::option::Option<unsafe extern "C" fn(hWndSciter: HWND, mediaType: LPCWSTR) -> SBOOL>,
    pub SciterSetMediaVars: ::core::option::Option<
        unsafe extern "C" fn(hWndSciter: HWND, mediaVars: *const SCITER_VALUE) -> SBOOL,
    >,
    pub SciterGetMinWidth: ::core::option::Option<unsafe extern "C" fn(hWndSciter: HWND) -> UINT>,
    pub SciterGetMinHeight:
        ::core::option::Option<unsafe extern "C" fn(hWndSciter: HWND, width: UINT) -> UINT>,
    pub SciterCall: ::core::option::Option<
        unsafe extern "C" fn(
            hWnd: HWND,
            functionName: LPCSTR,
            argc: UINT,
            argv: *const SCITER_VALUE,
            retval: *mut SCITER_VALUE,
        ) -> SBOOL,
    >,
    pub SciterEval: ::core::option::Option<
        unsafe extern "C" fn(
            hwnd: HWND,
            script: LPCWSTR,
            scriptLength: UINT,
            pretval: *mut SCITER_VALUE,
        ) -> SBOOL,
    >,
    pub SciterUpdateWindow: ::core::option::Option<unsafe extern "C" fn(hwnd: HWND)>,
    pub SciterTranslateMessage: LPVOID,
    pub SciterSetOption: ::core::option::Option<
        unsafe extern "C" fn(hWnd: HWND, option: UINT, value: UINT_PTR) -> SBOOL,
    >,
    pub SciterGetPPI: ::core::option::Option<
        unsafe extern "C" fn(hWndSciter: HWND, px: *mut UINT, py: *mut UINT),
    >,
    pub SciterGetViewExpando:
        ::core::option::Option<unsafe extern "C" fn(hwnd: HWND, pval: *mut VALUE) -> SBOOL>,
    pub SciterRenderD2D: LPVOID,
    pub SciterD2DFactory: LPVOID,
    pub SciterDWFactory: LPVOID,
    pub SciterGraphicsCaps: ::core::option::Option<unsafe extern "C" fn(pcaps: LPUINT) -> SBOOL>,
    pub SciterSetHomeURL:
        ::core::option::Option<unsafe extern "C" fn(hWndSciter: HWND, baseUrl: LPCWSTR) -> SBOOL>,
    pub SciterCreateNSView: LPVOID,
    pub SciterCreateWidget: LPVOID,
    pub SciterCreateWindow: ::core::option::Option<
        unsafe extern "C" fn(
            creationFlags: UINT,
            frame: LPRECT,
            arg1: LPVOID,
            arg2: LPVOID,
            parent: HWND,
        ) -> HWND,
    >,
    pub SciterSetupDebugOutput: ::core::option::Option<
        unsafe extern "C" fn(hwndOrNull: HWND, param: LPVOID, pfOutput: DEBUG_OUTPUT_PROC),
    >,
    pub Sciter_UseElement: ::core::option::Option<unsafe extern "C" fn(he: HELEMENT) -> INT>,
    pub Sciter_UnuseElement: ::core::option::Option<unsafe extern "C" fn(he: HELEMENT) -> INT>,
    pub SciterGetRootElement:
        ::core::option::Option<unsafe extern "C" fn(hwnd: HWND, phe: *mut HELEMENT) -> INT>,
    pub SciterGetFocusElement:
        ::core::option::Option<unsafe extern "C" fn(hwnd: HWND, phe: *mut HELEMENT) -> INT>,
    pub SciterFindElement: ::core::option::Option<
        unsafe extern "C" fn(hwnd: HWND, pt: POINT, phe: *mut HELEMENT) -> INT,
    >,
    pub SciterGetChildrenCount:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, count: *mut UINT) -> INT>,
    pub SciterGetNthChild: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, n: UINT, phe: *mut HELEMENT) -> INT,
    >,
    pub SciterGetParentElement: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, p_parent_he: *mut HELEMENT) -> INT,
    >,
    pub SciterGetElementHtmlCB: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            outer: SBOOL,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCBYTE, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> INT,
    >,
    pub SciterGetElementTextCB: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> INT,
    >,
    pub SciterSetElementText: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, utf16: LPCWSTR, length: UINT) -> INT,
    >,
    pub SciterGetAttributeCount:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, p_count: LPUINT) -> INT>,
    pub SciterGetNthAttributeNameCB: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            n: UINT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> INT,
    >,
    pub SciterGetNthAttributeValueCB: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            n: UINT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> INT,
    >,
    pub SciterGetAttributeByNameCB: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            name: LPCSTR,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> INT,
    >,
    pub SciterSetAttributeByName: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, name: LPCSTR, value: LPCWSTR) -> INT,
    >,
    pub SciterClearAttributes: ::core::option::Option<unsafe extern "C" fn(he: HELEMENT) -> INT>,
    pub SciterGetElementIndex:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, p_index: LPUINT) -> INT>,
    pub SciterGetElementType:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, p_type: *mut LPCSTR) -> INT>,
    pub SciterGetElementTypeCB: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> INT,
    >,
    pub SciterGetStyleAttributeCB: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            name: LPCSTR,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> INT,
    >,
    pub SciterSetStyleAttribute: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, name: LPCSTR, value: LPCWSTR) -> INT,
    >,
    pub SciterGetElementLocation: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, p_location: LPRECT, areas: UINT) -> INT,
    >,
    pub SciterScrollToView:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, SciterScrollFlags: UINT) -> INT>,
    pub SciterUpdateElement:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, andForceRender: SBOOL) -> INT>,
    pub SciterRefreshElementArea:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, rc: RECT) -> INT>,
    pub SciterSetCapture: ::core::option::Option<unsafe extern "C" fn(he: HELEMENT) -> INT>,
    pub SciterReleaseCapture: ::core::option::Option<unsafe extern "C" fn(he: HELEMENT) -> INT>,
    pub SciterGetElementHwnd: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, p_hwnd: *mut HWND, rootWindow: SBOOL) -> INT,
    >,
    pub SciterCombineURL: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, szUrlBuffer: LPWSTR, UrlBufferSize: UINT) -> INT,
    >,
    pub SciterSelectElements: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            CSS_selectors: LPCSTR,
            callback: ::core::option::Option<
                unsafe extern "C" fn(arg1: HELEMENT, arg2: LPVOID) -> SBOOL,
            >,
            param: LPVOID,
        ) -> INT,
    >,
    pub SciterSelectElementsW: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            CSS_selectors: LPCWSTR,
            callback: ::core::option::Option<
                unsafe extern "C" fn(arg1: HELEMENT, arg2: LPVOID) -> SBOOL,
            >,
            param: LPVOID,
        ) -> INT,
    >,
    pub SciterSelectParent: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            selector: LPCSTR,
            depth: UINT,
            heFound: *mut HELEMENT,
        ) -> INT,
    >,
    pub SciterSelectParentW: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            selector: LPCWSTR,
            depth: UINT,
            heFound: *mut HELEMENT,
        ) -> INT,
    >,
    pub SciterSetElementHtml: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            html: *const BYTE,
            htmlLength: UINT,
            where_: UINT,
        ) -> INT,
    >,
    pub SciterGetElementUID:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, puid: *mut UINT) -> INT>,
    pub SciterGetElementByUID: ::core::option::Option<
        unsafe extern "C" fn(hwnd: HWND, uid: UINT, phe: *mut HELEMENT) -> INT,
    >,
    pub SciterShowPopup: ::core::option::Option<
        unsafe extern "C" fn(hePopup: HELEMENT, heAnchor: HELEMENT, placement: UINT) -> INT,
    >,
    pub SciterShowPopupAt: ::core::option::Option<
        unsafe extern "C" fn(hePopup: HELEMENT, pos: POINT, placement: UINT) -> INT,
    >,
    pub SciterHidePopup: ::core::option::Option<unsafe extern "C" fn(he: HELEMENT) -> INT>,
    pub SciterGetElementState:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, pstateBits: *mut UINT) -> INT>,
    pub SciterSetElementState: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            stateBitsToSet: UINT,
            stateBitsToClear: UINT,
            updateView: SBOOL,
        ) -> INT,
    >,
    pub SciterCreateElement: ::core::option::Option<
        unsafe extern "C" fn(tagname: LPCSTR, textOrNull: LPCWSTR, phe: *mut HELEMENT) -> INT,
    >,
    pub SciterCloneElement:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, phe: *mut HELEMENT) -> INT>,
    pub SciterInsertElement: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, hparent: HELEMENT, index: UINT) -> INT,
    >,
    pub SciterDetachElement: ::core::option::Option<unsafe extern "C" fn(he: HELEMENT) -> INT>,
    pub SciterDeleteElement: ::core::option::Option<unsafe extern "C" fn(he: HELEMENT) -> INT>,
    pub SciterSetTimer: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, milliseconds: UINT, timer_id: UINT_PTR) -> INT,
    >,
    pub SciterDetachEventHandler: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, pep: LPELEMENT_EVENT_PROC, tag: LPVOID) -> INT,
    >,
    pub SciterAttachEventHandler: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, pep: LPELEMENT_EVENT_PROC, tag: LPVOID) -> INT,
    >,
    pub SciterWindowAttachEventHandler: ::core::option::Option<
        unsafe extern "C" fn(
            hwndLayout: HWND,
            pep: LPELEMENT_EVENT_PROC,
            tag: LPVOID,
            subscription: UINT,
        ) -> INT,
    >,
    pub SciterWindowDetachEventHandler: ::core::option::Option<
        unsafe extern "C" fn(hwndLayout: HWND, pep: LPELEMENT_EVENT_PROC, tag: LPVOID) -> INT,
    >,
    pub SciterSendEvent: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            appEventCode: UINT,
            heSource: HELEMENT,
            reason: UINT_PTR,
            handled: *mut SBOOL,
        ) -> INT,
    >,
    pub SciterPostEvent: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            appEventCode: UINT,
            heSource: HELEMENT,
            reason: UINT_PTR,
        ) -> INT,
    >,
    pub SciterCallBehaviorMethod: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, params: *mut METHOD_PARAMS) -> INT,
    >,
    pub SciterRequestElementData: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            url: LPCWSTR,
            dataType: UINT,
            initiator: HELEMENT,
        ) -> INT,
    >,
    pub SciterHttpRequest: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            url: LPCWSTR,
            dataType: UINT,
            requestType: UINT,
            requestParams: *mut REQUEST_PARAM,
            nParams: UINT,
        ) -> INT,
    >,
    pub SciterGetScrollInfo: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            scrollPos: LPPOINT,
            viewRect: LPRECT,
            contentSize: LPSIZE,
        ) -> INT,
    >,
    pub SciterSetScrollPos: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, scrollPos: POINT, smooth: SBOOL) -> INT,
    >,
    pub SciterGetElementIntrinsicWidths: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, pMinWidth: *mut INT, pMaxWidth: *mut INT) -> INT,
    >,
    pub SciterGetElementIntrinsicHeight: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, forWidth: INT, pHeight: *mut INT) -> INT,
    >,
    pub SciterIsElementVisible:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, pVisible: *mut SBOOL) -> INT>,
    pub SciterIsElementEnabled:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, pEnabled: *mut SBOOL) -> INT>,
    pub SciterSortElements: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            firstIndex: UINT,
            lastIndex: UINT,
            cmpFunc: ::core::option::Option<
                unsafe extern "C" fn(arg1: HELEMENT, arg2: HELEMENT, arg3: LPVOID) -> INT,
            >,
            cmpFuncParam: LPVOID,
        ) -> INT,
    >,
    pub SciterSwapElements:
        ::core::option::Option<unsafe extern "C" fn(he1: HELEMENT, he2: HELEMENT) -> INT>,
    pub SciterTraverseUIEvent: ::core::option::Option<
        unsafe extern "C" fn(evt: UINT, eventCtlStruct: LPVOID, bOutProcessed: *mut SBOOL) -> INT,
    >,
    pub SciterCallScriptingMethod: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            name: LPCSTR,
            argv: *const VALUE,
            argc: UINT,
            retval: *mut VALUE,
        ) -> INT,
    >,
    pub SciterCallScriptingFunction: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            name: LPCSTR,
            argv: *const VALUE,
            argc: UINT,
            retval: *mut VALUE,
        ) -> INT,
    >,
    pub SciterEvalElementScript: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            script: LPCWSTR,
            scriptLength: UINT,
            retval: *mut VALUE,
        ) -> INT,
    >,
    pub SciterAttachHwndToElement:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, hwnd: HWND) -> INT>,
    pub SciterControlGetType:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, pType: *mut UINT) -> INT>,
    pub SciterGetValue:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, pval: *mut VALUE) -> INT>,
    pub SciterSetValue:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, pval: *const VALUE) -> INT>,
    pub SciterGetExpando: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, pval: *mut VALUE, forceCreation: SBOOL) -> INT,
    >,
    pub SciterGetObject: ::core::option::Option<
        unsafe extern "C" fn(
            he: HELEMENT,
            pval: *mut ::core::ffi::c_void,
            forceCreation: SBOOL,
        ) -> INT,
    >,
    pub SciterGetElementNamespace: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, pval: *mut ::core::ffi::c_void) -> INT,
    >,
    pub SciterGetHighlightedElement:
        ::core::option::Option<unsafe extern "C" fn(hwnd: HWND, phe: *mut HELEMENT) -> INT>,
    pub SciterSetHighlightedElement:
        ::core::option::Option<unsafe extern "C" fn(hwnd: HWND, he: HELEMENT) -> INT>,
    pub SciterNodeAddRef: ::core::option::Option<unsafe extern "C" fn(hn: HNODE) -> INT>,
    pub SciterNodeRelease: ::core::option::Option<unsafe extern "C" fn(hn: HNODE) -> INT>,
    pub SciterNodeCastFromElement:
        ::core::option::Option<unsafe extern "C" fn(he: HELEMENT, phn: *mut HNODE) -> INT>,
    pub SciterNodeCastToElement:
        ::core::option::Option<unsafe extern "C" fn(hn: HNODE, he: *mut HELEMENT) -> INT>,
    pub SciterNodeFirstChild:
        ::core::option::Option<unsafe extern "C" fn(hn: HNODE, phn: *mut HNODE) -> INT>,
    pub SciterNodeLastChild:
        ::core::option::Option<unsafe extern "C" fn(hn: HNODE, phn: *mut HNODE) -> INT>,
    pub SciterNodeNextSibling:
        ::core::option::Option<unsafe extern "C" fn(hn: HNODE, phn: *mut HNODE) -> INT>,
    pub SciterNodePrevSibling:
        ::core::option::Option<unsafe extern "C" fn(hn: HNODE, phn: *mut HNODE) -> INT>,
    pub SciterNodeParent:
        ::core::option::Option<unsafe extern "C" fn(hnode: HNODE, pheParent: *mut HELEMENT) -> INT>,
    pub SciterNodeNthChild:
        ::core::option::Option<unsafe extern "C" fn(hnode: HNODE, n: UINT, phn: *mut HNODE) -> INT>,
    pub SciterNodeChildrenCount:
        ::core::option::Option<unsafe extern "C" fn(hnode: HNODE, pn: *mut UINT) -> INT>,
    pub SciterNodeType:
        ::core::option::Option<unsafe extern "C" fn(hnode: HNODE, pNodeType: *mut UINT) -> INT>,
    pub SciterNodeGetText: ::core::option::Option<
        unsafe extern "C" fn(
            hnode: HNODE,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCWSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> INT,
    >,
    pub SciterNodeSetText: ::core::option::Option<
        unsafe extern "C" fn(hnode: HNODE, text: LPCWSTR, textLength: UINT) -> INT,
    >,
    pub SciterNodeInsert: ::core::option::Option<
        unsafe extern "C" fn(hnode: HNODE, where_: UINT, what: HNODE) -> INT,
    >,
    pub SciterNodeRemove:
        ::core::option::Option<unsafe extern "C" fn(hnode: HNODE, finalize: SBOOL) -> INT>,
    pub SciterCreateTextNode: ::core::option::Option<
        unsafe extern "C" fn(text: LPCWSTR, textLength: UINT, phnode: *mut HNODE) -> INT,
    >,
    pub SciterCreateCommentNode: ::core::option::Option<
        unsafe extern "C" fn(text: LPCWSTR, textLength: UINT, phnode: *mut HNODE) -> INT,
    >,
    pub ValueInit: ::core::option::Option<unsafe extern "C" fn(pval: *mut VALUE) -> UINT>,
    pub ValueClear: ::core::option::Option<unsafe extern "C" fn(pval: *mut VALUE) -> UINT>,
    pub ValueCompare: ::core::option::Option<
        unsafe extern "C" fn(pval1: *const VALUE, pval2: *const VALUE) -> UINT,
    >,
    pub ValueCopy:
        ::core::option::Option<unsafe extern "C" fn(pdst: *mut VALUE, psrc: *const VALUE) -> UINT>,
    pub ValueIsolate: ::core::option::Option<unsafe extern "C" fn(pdst: *mut VALUE) -> UINT>,
    pub ValueType: ::core::option::Option<
        unsafe extern "C" fn(pval: *const VALUE, pType: *mut UINT, pUnits: *mut UINT) -> UINT,
    >,
    pub ValueStringData: ::core::option::Option<
        unsafe extern "C" fn(
            pval: *const VALUE,
            pChars: *mut LPCWSTR,
            pNumChars: *mut UINT,
        ) -> UINT,
    >,
    pub ValueStringDataSet: ::core::option::Option<
        unsafe extern "C" fn(pval: *mut VALUE, chars: LPCWSTR, numChars: UINT, units: UINT) -> UINT,
    >,
    pub ValueIntData:
        ::core::option::Option<unsafe extern "C" fn(pval: *const VALUE, pData: *mut INT) -> UINT>,
    pub ValueIntDataSet: ::core::option::Option<
        unsafe extern "C" fn(pval: *mut VALUE, data: INT, type_: UINT, units: UINT) -> UINT,
    >,
    pub ValueInt64Data:
        ::core::option::Option<unsafe extern "C" fn(pval: *const VALUE, pData: *mut INT64) -> UINT>,
    pub ValueInt64DataSet: ::core::option::Option<
        unsafe extern "C" fn(pval: *mut VALUE, data: INT64, type_: UINT, units: UINT) -> UINT,
    >,
    pub ValueFloatData:
        ::core::option::Option<unsafe extern "C" fn(pval: *const VALUE, pData: *mut f64) -> UINT>,
    pub ValueFloatDataSet: ::core::option::Option<
        unsafe extern "C" fn(pval: *mut VALUE, data: f64, type_: UINT, units: UINT) -> UINT,
    >,
    pub ValueBinaryData: ::core::option::Option<
        unsafe extern "C" fn(pval: *const VALUE, pBytes: *mut LPCBYTE, pnBytes: *mut UINT) -> UINT,
    >,
    pub ValueBinaryDataSet: ::core::option::Option<
        unsafe extern "C" fn(
            pval: *mut VALUE,
            pBytes: LPCBYTE,
            nBytes: UINT,
            type_: UINT,
            units: UINT,
        ) -> UINT,
    >,
    pub ValueElementsCount:
        ::core::option::Option<unsafe extern "C" fn(pval: *const VALUE, pn: *mut INT) -> UINT>,
    pub ValueNthElementValue: ::core::option::Option<
        unsafe extern "C" fn(pval: *const VALUE, n: INT, pretval: *mut VALUE) -> UINT,
    >,
    pub ValueNthElementValueSet: ::core::option::Option<
        unsafe extern "C" fn(pval: *mut VALUE, n: INT, pval_to_set: *const VALUE) -> UINT,
    >,
    pub ValueNthElementKey: ::core::option::Option<
        unsafe extern "C" fn(pval: *const VALUE, n: INT, pretval: *mut VALUE) -> UINT,
    >,
    pub ValueEnumElements: ::core::option::Option<
        unsafe extern "C" fn(
            pval: *const VALUE,
            penum: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPVOID, arg2: *const VALUE, arg3: *const VALUE) -> SBOOL,
            >,
            param: LPVOID,
        ) -> UINT,
    >,
    pub ValueSetValueToKey: ::core::option::Option<
        unsafe extern "C" fn(
            pval: *mut VALUE,
            pkey: *const VALUE,
            pval_to_set: *const VALUE,
        ) -> UINT,
    >,
    pub ValueGetValueOfKey: ::core::option::Option<
        unsafe extern "C" fn(pval: *const VALUE, pkey: *const VALUE, pretval: *mut VALUE) -> UINT,
    >,
    pub ValueToString:
        ::core::option::Option<unsafe extern "C" fn(pval: *mut VALUE, how: UINT) -> UINT>,
    pub ValueFromString: ::core::option::Option<
        unsafe extern "C" fn(pval: *mut VALUE, str_: LPCWSTR, strLength: UINT, how: UINT) -> UINT,
    >,
    pub ValueInvoke: ::core::option::Option<
        unsafe extern "C" fn(
            pval: *const VALUE,
            pthis: *mut VALUE,
            argc: UINT,
            argv: *const VALUE,
            pretval: *mut VALUE,
            url: LPCWSTR,
        ) -> UINT,
    >,
    pub ValueNativeFunctorSet: ::core::option::Option<
        unsafe extern "C" fn(
            pval: *mut VALUE,
            pinvoke: NATIVE_FUNCTOR_INVOKE,
            prelease: NATIVE_FUNCTOR_RELEASE,
            tag: *mut ::core::ffi::c_void,
        ) -> UINT,
    >,
    pub ValueIsNativeFunctor:
        ::core::option::Option<unsafe extern "C" fn(pval: *const VALUE) -> SBOOL>,
    pub reserved1: LPVOID,
    pub reserved2: LPVOID,
    pub reserved3: LPVOID,
    pub reserved4: LPVOID,
    pub SciterOpenArchive: ::core::option::Option<
        unsafe extern "C" fn(archiveData: LPCBYTE, archiveDataLength: UINT) -> HSARCHIVE,
    >,
    pub SciterGetArchiveItem: ::core::option::Option<
        unsafe extern "C" fn(
            harc: HSARCHIVE,
            path: LPCWSTR,
            pdata: *mut LPCBYTE,
            pdataLength: *mut UINT,
        ) -> SBOOL,
    >,
    pub SciterCloseArchive: ::core::option::Option<unsafe extern "C" fn(harc: HSARCHIVE) -> SBOOL>,
    pub SciterFireEvent: ::core::option::Option<
        unsafe extern "C" fn(
            evt: *const BEHAVIOR_EVENT_PARAMS,
            post: SBOOL,
            handled: *mut SBOOL,
        ) -> INT,
    >,
    pub SciterGetCallbackParam: ::core::option::Option<unsafe extern "C" fn(hwnd: HWND) -> LPVOID>,
    pub SciterPostCallback: ::core::option::Option<
        unsafe extern "C" fn(
            hwnd: HWND,
            wparam: UINT_PTR,
            lparam: UINT_PTR,
            timeoutms: UINT,
        ) -> UINT_PTR,
    >,
    pub GetSciterGraphicsAPI: ::core::option::Option<unsafe extern "C" fn() -> LPSciterGraphicsAPI>,
    pub GetSciterRequestAPI: ::core::option::Option<unsafe extern "C" fn() -> LPSciterRequestAPI>,
    pub SciterCreateOnDirectXWindow: LPVOID,
    pub SciterRenderOnDirectXWindow: LPVOID,
    pub SciterRenderOnDirectXTexture: LPVOID,
    pub SciterProcX:
        ::core::option::Option<unsafe extern "C" fn(hwnd: HWND, pMsg: *mut SCITER_X_MSG) -> SBOOL>,
    pub SciterAtomValue:
        ::core::option::Option<unsafe extern "C" fn(name: *const ::core::ffi::c_char) -> UINT64>,
    pub SciterAtomNameCB: ::core::option::Option<
        unsafe extern "C" fn(
            atomv: UINT64,
            rcv: ::core::option::Option<
                unsafe extern "C" fn(arg1: LPCSTR, arg2: UINT, arg3: LPVOID),
            >,
            rcv_param: LPVOID,
        ) -> SBOOL,
    >,
    pub SciterSetGlobalAsset:
        ::core::option::Option<unsafe extern "C" fn(pass: *mut som_asset_t) -> SBOOL>,
    pub SciterGetElementAsset: ::core::option::Option<
        unsafe extern "C" fn(el: HELEMENT, nameAtom: UINT64, ppass: *mut *mut som_asset_t) -> INT,
    >,
    pub SciterSetVariable: ::core::option::Option<
        unsafe extern "C" fn(hwndOrNull: HWND, name: LPCSTR, pvalToSet: *const VALUE) -> UINT,
    >,
    pub SciterGetVariable: ::core::option::Option<
        unsafe extern "C" fn(hwndOrNull: HWND, name: LPCSTR, pvalToGet: *mut VALUE) -> UINT,
    >,
    pub SciterElementUnwrap: ::core::option::Option<
        unsafe extern "C" fn(pval: *const VALUE, ppElement: *mut HELEMENT) -> UINT,
    >,
    pub SciterElementWrap:
        ::core::option::Option<unsafe extern "C" fn(pval: *mut VALUE, pElement: HELEMENT) -> UINT>,
    pub SciterNodeUnwrap: ::core::option::Option<
        unsafe extern "C" fn(pval: *const VALUE, ppNode: *mut HNODE) -> UINT,
    >,
    pub SciterNodeWrap:
        ::core::option::Option<unsafe extern "C" fn(pval: *mut VALUE, pNode: HNODE) -> UINT>,
    pub SciterReleaseGlobalAsset:
        ::core::option::Option<unsafe extern "C" fn(pass: *mut som_asset_t) -> SBOOL>,
    pub SciterExec: ::core::option::Option<
        unsafe extern "C" fn(appCmd: UINT, p1: UINT_PTR, p2: UINT_PTR) -> INT_PTR,
    >,
    pub SciterWindowExec: ::core::option::Option<
        unsafe extern "C" fn(hwnd: HWND, windowCmd: UINT, p1: UINT_PTR, p2: UINT_PTR) -> INT_PTR,
    >,
    pub SciterEGLGetProcAddress: ::core::option::Option<
        unsafe extern "C" fn(procName: *const ::core::ffi::c_char) -> proc_ptr_t,
    >,
    pub SciterEGLSendEvent: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, eventCode: UINT, reason: UINT_PTR) -> INT,
    >,
    pub SciterRequestAnimationFrameEvent: ::core::option::Option<
        unsafe extern "C" fn(he: HELEMENT, eventCode: UINT, reason: UINT_PTR) -> INT,
    >,
    pub SciterRequestPaint: ::core::option::Option<unsafe extern "C" fn(he: HELEMENT) -> INT>,
}
pub type ISciterAPI = _ISciterAPI;
